services:
  open-webui:
    build:
      context: .
      dockerfile: Dockerfile
    image: ghcr.io/open-webui/open-webui:${WEBUI_DOCKER_TAG-main}
    container_name: adaptive-gateway-webui-custom
    volumes:
      - adaptive-gateway_webui_data:/app/backend/data
    ports:
      - ${OPEN_WEBUI_PORT-3001}:8080
    environment:
      - 'OPENAI_API_BASE_URLS=http://adaptive-gateway-litellm:4000/v1'
      - 'OPENAI_API_KEYS=sk-admin-gateway-2024'
      - 'ENABLE_OPENAI_API=True'
      - 'ENABLE_OLLAMA_API=False'
      - 'WEBUI_SECRET_KEY='
    networks:
      - default
      - gateway
    restart: unless-stopped

volumes:
  adaptive-gateway_webui_data:
    external: true

networks:
  gateway:
    external: true
    name: adaptive-gateway_default
